name: Build code

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:  
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Arudino cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          export PATH=$(pwd)/bin
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install OneWire Servo Time TinyGPS
      - name: Build Code
        run: |
          arduino-cli compile -b arduino:avr:uno example-control-system.ino
        
